### ISSUE TITLE
Can't download script because of Microsoft Defender

### ISSUE THREAD

**Issue by rpbush** [crutkas/setup#2]
https://www.microsoft.com/en-us/wdsi/threats/malware-encyclopedia-description?name=Trojan%3AScript%2FUlthar.A!ml&threatid=2147751841

**Comment by crutkas** [comment]
?

**Comment by rpbush** [comment]
You should be able to reproduce it by trying to download the script directly. Obviously, I forked and copy and pasted into a created file locally.

Great project!

**Comment by crutkas** [comment]
What file is throwing that?  What virus scanner. 

Everything here is a basic text file too so that is very odd

**Comment by rpbush** [comment]
When I click download zip, but even if I try to download just the ps1 file it still blocks me.

Kind regards,
Ryan Bush

________________________________

**Comment by crutkas** [comment]
I can't repro this issue.  I cloned as well grabbing the zip via the github dropdown.  I'm wondering if maybe running windows update to get latest definitions could help.
